# callbacks configuration

callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    validation_path: null
    prediction_confs:
      - name: "span"
        limit: -1
        path: null
        token_batch_size: 2048
        enabled_prediction_callbacks:
          - "span"
    prediction_callbacks:
      span:
        _target_: "src.span_f1_callback.SpanF1PredictionCallback"
    prediction_dataset_conf: ${prediction.dataset}
