# model configuration
model:
  _target_: src.model.CRFPLModule
  transformer_model: ${transformer_model}
  dropout: 0.5
  use_last_n_layers: 4
  fine_tune: False
  lstm_layers: 2
  lstm_hidden_size: 512
  lstm_bidirectional: True

  # optimizer configuration
  optim_conf:
    _target_: src.optim_adamax.AdamaxFactory
    lr: 3e-5
    warmup_steps: 5000
    total_steps: ${training.pl_trainer.max_steps}
    weight_decay: 0.01

# evaluation
evaluation:
  _target_: src.span_f1_evaluation.SpanF1Evaluation

# new dataset configuration
data:
  datamodule:
    train_dataset:
      _target_: 'src.noisy_ner_dataset.NoisyNERDataset.from_file'
      noisification_probability: 0.5
      transformer_model: ${transformer_model}
      min_length: -1
      max_length: 500
      tokens_per_batch: 1000
      max_batch_size: 10
      section_size: 10000
      prebatch: True
      materialize: False
      for_inference: False
    validation_dataset:
      _target_: 'src.noisy_ner_dataset.NoisyNERDataset.from_file'
      noisification_probability: 0.0
      transformer_model: ${transformer_model}
      min_length: -1
      max_length: 500
      tokens_per_batch: 1000
      max_batch_size: 10
      section_size: 10000
      prebatch: True
      materialize: True
      for_inference: True
