# model configuration
model:
  _target_: src.model.CRFPLModule
  transformer_model: ${transformer_model}
  dropout: 0.5
  use_last_n_layers: 4
  fine_tune: False
  lstm_layers: 2
  lstm_hidden_size: 512
  lstm_bidirectional: True

  # optimizer configuration
  optim_conf:
    _target_: src.optim_adamax.AdamaxFactory
    lr: 3e-5
    warmup_steps: 5000
    total_steps: ${training.pl_trainer.max_steps}
    weight_decay: 0.01

# callbacks configuration
callbacks_monitor: span_f1

callbacks:
  callbacks:
    - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
      validation_path: null
      prediction_confs:
        - name: "span"
          limit: -1
          path: null
          token_batch_size: 2048
          enabled_prediction_callbacks:
            - "span"
      prediction_callbacks:
        span:
          _target_: "src.span_f1_callback.SpanF1PredictionCallback"
      prediction_dataset_conf: ${prediction.dataset}


# new dataset configuration
data:
  datamodule:
    train_dataset:
      _target_: 'src.noisy_ner_dataset.NoisyNERDataset.from_file'
      noisification_probability: 0.5
      transformer_model: ${transformer_model}
      min_length: -1
      max_length: 500
      tokens_per_batch: 1000
      max_batch_size: 10
      section_size: 10000
      prebatch: True
      materialize: False
      for_inference: False
    validation_dataset:
      _target_: 'src.noisy_ner_dataset.NoisyNERDataset.from_file'
      noisification_probability: 0.0
      transformer_model: ${transformer_model}
      min_length: -1
      max_length: 500
      tokens_per_batch: 1000
      max_batch_size: 10
      section_size: 10000
      prebatch: True
      materialize: True
      for_inference: True
