# model configuration
_target_: src.model.CRFPLModule
transformer_model: ${transformer_model}
dropout: 0.5
use_last_n_layers: 4
fine_tune: False
lstm_layers: 2
lstm_hidden_size: 512
lstm_bidirectional: True

# optimizer configuration
optim_conf:
  _target_: src.optim_adamax.AdamaxFactory
  lr: 3e-5
  warmup_steps: 5000
  total_steps: ${training.pl_trainer.max_steps}
  weight_decay: 0.01
